add(hashable): Hashable / Hasher
NSHipster/articles-zh-Hans pull request #12
Opened 2018-09-30 03:52 UTC by Damonvvong

2018-10-08 09:48 UTC, croath requested changes

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +根据一份来自某位前零售店员工的报告表示，对于顾客的描述有着严格的指导方针。他们的外貌特征如：年龄、性别、种族、身高都没有被使用 —— 甚至连头发的颜色都没有被使用。而是通过顾客的着装来描述，例如“黑色的高领毛衣，牛仔裤和眼镜”
某位前零售店员工的 -> 零售店某位前员工的

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +根据一份来自某位前零售店员工的报告表示，对于顾客的描述有着严格的指导方针。他们的外貌特征如：年龄、性别、种族、身高都没有被使用 —— 甚至连头发的颜色都没有被使用。而是通过顾客的着装来描述，例如“黑色的高领毛衣，牛仔裤和眼镜”
句尾句号

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +这种描述顾客的方式和编程中的哈希函数有很多共同之处。同许多优秀的哈希函数一样，它是连续和易计算的，可用于快速找到你正在寻找的内容（或者人）。这比使用队列要好多了，我想你一定会同意的。
我想你肯定也觉得这样比......

中文一般这样说比较顺一点吧

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +在 **Swift** 之前的版本中，为了让自定义类型能支持 `Set` 或 `Dictionary` 存储需要写⼤量的 [样板代码](https://nshipster.com/swift-gyb/)。
已经有中文翻译了 https://nshipster.cn/swift-gyb/

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +对于大多数开发者⽽⾔，实现 `Hashable` 只是为了能尽快让要做的事情步入正轨，因此他们会对所有的存储属性使⽤[异或](https://en.wikipedia.org/wiki/Exclusive_or)操作，并在某一天调用它。
文章中有很多 Wikipedia 的链接，如果对应的中文版本 wiki 内容足够充足的话，可以引用中文的

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +**Swift 4.2** 通过引入 `Hasher` 类型并采用新的通用哈希函数进一步优化 `Hashable`
我看到原文这些地方都没有 ** 标记，所有和原文不一样的样式都去掉吧，地方比较多，不一一指出了

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +**Swift 4.2** 中的哈希函数是基于伪随机函数族 [SipHash](https://en.wikipedia.org/wiki/SipHash) 实现的，特别是 [SipHash-1-3 and SipHash-2-4](https://github.com/apple/swift/blob/master/stdlib/public/core/SipHash.swift)，每个消息块
不是【分别】有，就是有 3 或 4 个 ....

【最后决定】这个有问题，这里指的是 finalizing rounds，不翻译也可以，如果翻译的话可以称作最终轮之类的，但肯定不是【最后决定】。

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +你不应该依赖特定的哈希值或者在执行中保存它们。在极少数情况下，你确定要这么做的话，可以设置标识符 SWIFT_DETERMINISTIC_HASHING 以禁用随机哈希种子。
可以更中文化一点，我觉得中国人是不这么说话的。稍微改改无关紧要的词语让句子更通顺起来。

比方说：
1.【你不应该依赖特定的哈希值或者在执行中保存它们】中国人说话可能会这么说【你不应该依赖特定的哈希值，也不应该在程序执行中保存特定的哈希值】
2. 【可以设置标识符 SWIFT_DETERMINISTIC_HASHING】，中文是不是习惯顺序调转一下？【可以设置 SWIFT_DETERMINISTIC_HASHING 标识符】

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +也就是说...亲爱的读者，在下次您访问当地的苹果零售店时，我不鼓励你和你的朋友协调服饰，以试图在天才吧中制造混乱和不和谐。
这里也请调整一下语序和句子结构

2018-10-08 09:48 UTC, croath commented on 2018-08-13-hashable.md
> +当你在天才吧等候的时候，远离那些和自己穿同色衬衫的人。这会让每个人做事都变得容易得多。
远离这句 -> 和穿同样颜色衣服的人站得远一点

2018-10-08 12:56 UTC, Damonvvong commented
@croath 已根据修改意见修改

2018-10-09 02:15 UTC, croath requested changes

2018-10-09 02:15 UTC, croath commented on 2018-08-13-hashable.md
> +**Swift 4.2** 中的哈希函数是基于伪随机函数族 [SipHash](https://en.wikipedia.org/wiki/SipHash) 实现的，比如 [SipHash-1-3 and SipHash-2-4](https://github.com/apple/swift/blob/master/stdlib/public/core/SipHash.swift)，分别在每个消
**** 去掉

2018-10-09 02:15 UTC, croath commented
@aprilnov @rickytan

2018-10-09 02:39 UTC, aprilnov commented
LGTM

2018-10-09 03:44 UTC, Damonvvong commented
@croath 抱歉，遗漏掉了移除，已经做修改了

2018-10-09 09:33 UTC, merged