Translate NSDataAsset
NSHipster/articles-zh-Hans pull request #17
Opened 2018-11-16 02:31 UTC by mobilefellow

Translate [NSDataAsset](https://nshipster.com/nsdataasset/)

2019-01-27 06:08 UTC, croath requested changes

2019-01-27 06:08 UTC, croath commented on 2018-08-26-nsdataasset.md
> +除了提供更简便的 API，Asset Catalog 还允许 App 使用 [App 瘦身](https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f) 为每个用户设备提供一个经过优化的更小的安装包。
app thinning 是不是不用翻译..

2019-01-27 06:08 UTC, croath commented on 2018-08-26-nsdataasset.md
> +图片是最常见的 Asset 类型，但是从 iOS 9 和 macOS El Capitan 开始，JSON、XML 和其他数据文件之类的资源也可以通过 [`NSDataAsset`](https://developer.apple.com/documentation/uikit/nsdataasset) 加入到这种乐趣中。
`...之类的资源也可以通过这种有趣的方式参与进来` 这样是不是好一点？

2019-01-27 06:08 UTC, croath commented on 2018-08-26-nsdataasset.md
> +    有很多加速网络请求的技术：压缩和流技术、缓存和预加载、连接池和多路复用、延迟和后台运行。然而，还有一种比它们优先级更高，效果更好的优化策略：_不要在刚开始的地方发送请求_。
通读全文，我觉得这里的意思是，不要在最开始的地方进行所有请求，这样的话请求需要等待，如果请求失败的话 app 流程就会卡住无法进行，需要一种更快更好的方式来做这件事。

2019-01-28 07:13 UTC, skyline75489 commented on 2018-08-26-nsdataasset.md
> +有很多加速网络请求的技术：压缩和流技术、缓存和预加载、连接池和多路复用、延迟和后台运行。然而，还有一种比它们优先级更高，效果更好的优化策略：_不要在刚开始的地方发送请求_。
"不要在刚开始的地方发送请求" 不准确，原句意思是“一开始就不要发送请求”

2019-01-28 07:16 UTC, skyline75489 commented on 2018-08-26-nsdataasset.md
> +Asset Catalog 允许你根据当前设备的特点来组织资源文件。对于一个给定的图片，你可以根据设备（iPhone、iPad、Apple Watch、Apple TV、Mac）、屏幕分辨率（`@2x` / `@3x`）或者色域（sRGB / P3），提供不同的文件。对于其他类型的 asset，你可能根据可用内存或者 Metal 版本的不同而提供不同的文件。请求 asset 时仅需提供名字，最合
”characteristics“ 可否译为”属性“？“特点”感觉有些不明所以。device 和 resolution 并不是“特点”。

2019-01-28 07:19 UTC, skyline75489 commented on 2018-08-26-nsdataasset.md
> +虽然 Assets Catalog 会对 image asset 执行的无损压缩，但没有任何文档、Xcode 帮助或 WWDC 会议指出 data asset 上也存在这种优化（至少目前没有）。
“执行的无损压缩”， 多了一个“的”。  WWDC sessions 翻译为“会议”感觉有些重了，我觉得也可以不翻译

2019-01-28 07:20 UTC, skyline75489 commented on 2018-08-26-nsdataasset.md
> +尽管你倾向于认为你的所有用户都享受着快速的、无处不在的 WiFi 和 LTE 网络，但这并不适用于所有人，也不适用于所有时段。
原句的意思更多的是，“所有用户都享受着快速的、无处不在的 WiFi 和 LTE 网络” 这种想法本身是诱人的，本句翻译不是很准确。

2019-01-28 08:16 UTC, rickytan commented on 2018-08-26-nsdataasset.md
> +对于谷歌、亚马逊和 Netflix 这样的大型的互联网公司而言，这里和那里额外的一秒钟可能意味着年收入里的 _数十亿_ 美金。所以那些公司投入如此多的工程努力来让网页更快，也没有什么奇怪的了。
`here and there` 直译成 “这里和那里” 感觉有点看不懂，作者的意思可能是：用户停在上述网站，或者不停在上述网站一秒，here and there，将产生 xxx 的收区别

2019-01-28 08:16 UTC, rickytan commented on 2018-08-26-nsdataasset.md
> +有很多加速网络请求的技术：压缩和流技术、缓存和预加载、连接池和多路复用、延迟和后台运行。然而，还有一种比它们优先级更高，效果更好的优化策略：_不要在刚开始的地方发送请求_。
`in the first place` ，这里应该是“压根就不发请求”，不是刚开始

2019-01-28 08:16 UTC, rickytan commented on 2018-08-26-nsdataasset.md
> +有很多加速网络请求的技术：压缩和流技术、缓存和预加载、连接池和多路复用、延迟和后台运行。然而，还有一种比它们优先级更高，效果更好的优化策略：_不要在刚开始的地方发送请求_。
**excerpt** 里也一样

2019-01-28 08:16 UTC, rickytan commented on 2018-08-26-nsdataasset.md
> +默认情况下，Finder （访达）把这两种 bundle 都当做目录，以便在需要时查看和修改它们的内容。
`bundle` 要不要翻译成 **捆绑包** ？

2019-01-28 08:16 UTC, rickytan commented on 2018-08-26-nsdataasset.md
> +当你这么做时，Xcode 会把那个文件复制到 `.dataset` 子目录，并将它的文件名和 [通用类型标识符（Universal Type Identifier）](https://en.wikipedia.org/wiki/Uniform_Type_Identifier) 更新到 `contents.json` 元数据文件。
链接有中文版的：<https://zh.wikipedia.org/wiki/%E7%BB%9F%E4%B8%80%E7%B1%BB%E5%9E%8B%E6%A0%87%E8%AF%86>

2019-01-28 08:16 UTC, rickytan commented on 2018-08-26-nsdataasset.md
> +    有很多加速网络请求的技术：压缩和流技术、缓存和预加载、连接池和多路复用、延迟和后台运行。然而，还有一种比它们优先级更高，效果更好的优化策略：_不要在刚开始的地方发送请求_。
“压根就不发请求”

2019-01-28 11:14 UTC, mobilefellow commented on 2018-08-26-nsdataasset.md
> +    有很多加速网络请求的技术：压缩和流技术、缓存和预加载、连接池和多路复用、延迟和后台运行。然而，还有一种比它们优先级更高，效果更好的优化策略：_不要在刚开始的地方发送请求_。
好的，这样确实更加贴切

2019-01-28 11:14 UTC, mobilefellow commented on 2018-08-26-nsdataasset.md
> +有很多加速网络请求的技术：压缩和流技术、缓存和预加载、连接池和多路复用、延迟和后台运行。然而，还有一种比它们优先级更高，效果更好的优化策略：_不要在刚开始的地方发送请求_。
👌

2019-01-28 11:18 UTC, mobilefellow commented on 2018-08-26-nsdataasset.md
> +Asset Catalog 允许你根据当前设备的特点来组织资源文件。对于一个给定的图片，你可以根据设备（iPhone、iPad、Apple Watch、Apple TV、Mac）、屏幕分辨率（`@2x` / `@3x`）或者色域（sRGB / P3），提供不同的文件。对于其他类型的 asset，你可能根据可用内存或者 Metal 版本的不同而提供不同的文件。请求 asset 时仅需提供名字，最合
要不翻译成“特性”？“属性”会让人想到“property”

2019-01-28 11:49 UTC, mobilefellow commented on 2018-08-26-nsdataasset.md
> +对于谷歌、亚马逊和 Netflix 这样的大型的互联网公司而言，这里和那里额外的一秒钟可能意味着年收入里的 _数十亿_ 美金。所以那些公司投入如此多的工程努力来让网页更快，也没有什么奇怪的了。
这样直译确实让人有点误解，不过作者应该不是你理解的这样，后面的 “making the web fast” 和全文都在强调更快的加载速度，这都是减少 `用户停在上述网站` 的时间，那公司不是亏本了吗……

要不忽略 `here and there`，直接翻译为“加载时多花一秒钟就意味着损失数十亿美元的年收入”？

2019-01-28 11:49 UTC, mobilefellow commented on 2018-08-26-nsdataasset.md
> +有很多加速网络请求的技术：压缩和流技术、缓存和预加载、连接池和多路复用、延迟和后台运行。然而，还有一种比它们优先级更高，效果更好的优化策略：_不要在刚开始的地方发送请求_。
好的

2019-01-28 11:53 UTC, mobilefellow commented on 2018-08-26-nsdataasset.md
> +默认情况下，Finder （访达）把这两种 bundle 都当做目录，以便在需要时查看和修改它们的内容。
我也考虑过这个问题，但后来考虑到 bundler 有点像一个专有名词，经常出现于文档和代码中，程序员都看得懂，译为 `捆绑包` 反而会让人看不懂了。

2019-01-28 12:06 UTC, mobilefellow commented on 2018-08-26-nsdataasset.md
> +尽管你倾向于认为你的所有用户都享受着快速的、无处不在的 WiFi 和 LTE 网络，但这并不适用于所有人，也不适用于所有时段。
因为 “xxx想法很诱人” 这种翻译听起来有点怪，所以采用了现在的翻译，要不改为 “尽管人们容易认为所有用户都享受着快速的、无处不在的 WiFi 和 LTE 网络，但这并不适用于所有人，也不适用于所有时段。”？

2019-01-30 04:59 UTC, skyline75489 commented on 2018-08-26-nsdataasset.md
> +Asset Catalog 允许你根据当前设备的特点来组织资源文件。对于一个给定的图片，你可以根据设备（iPhone、iPad、Apple Watch、Apple TV、Mac）、屏幕分辨率（`@2x` / `@3x`）或者色域（sRGB / P3），提供不同的文件。对于其他类型的 asset，你可能根据可用内存或者 Metal 版本的不同而提供不同的文件。请求 asset 时仅需提供名字，最合
我觉得翻译成“特性” OK。

2019-02-11 12:48 UTC, croath commented
这里有更新吗？

2019-02-12 07:48 UTC, mobilefellow commented
> 这里有更新吗？

因为部分 comment 没有得到回复，所以还没提交更新。我接下来会按上面的 comment 提交一个最新的版本。

2019-02-12 16:10 UTC, croath commented
@mobilefellow 辛苦。

@rickytan @skyline75489 再看看？

2019-05-17 02:35 UTC, rickytan commented
删除英文原文

2019-05-19 08:49 UTC, mobilefellow commented
@rickytan 原文已删除

2019-05-19 10:34 UTC, merged