Swift property observers
NSHipster/articles-zh-Hans pull request #18
Opened 2018-11-16 06:31 UTC by wuqiuhao

2018-11-16 07:25 UTC, li-bei commented on 2018-08-20-swift-property-observers.md
> +到了 20 世纪 30 年代，Rube Goldberg 已成为家喻户晓的名字，与 [“自营餐巾”](https://upload.wikimedia.org/wikipedia/commons/a/a9/Rube_Goldberg%27s_%22Self-Operating_Napkin%22_%28cropped%29.gif) 等漫画中描绘的奇异复杂和异想天开的发明同义。大约在同一时期，阿
带链接的文字前后不用加额外的空格，中文里没有这个习惯

2018-11-16 07:25 UTC, li-bei commented on 2018-08-20-swift-property-observers.md
> +作为软件开发人员，我们提倡尽可能减少代码中的远程操作。这是根据一些众所周知的规范法则得出的，如 [单一职责原则](https://en.wikipedia.org/wiki/Single_responsibility_principle)、[最少意外原则](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) 和 [笛米特法
这些 wiki 有对应的中文版的话可以改到中文版链接

2018-11-16 07:25 UTC, li-bei commented on 2018-08-20-swift-property-observers.md
> +这是本周关于 Swift 属性观察文章的焦点，它提出了一种内置的轻量级替代方案，适用于更正式的解决方案，如模型 - 视图 - 视图模型（MVVM）函数响应式编程（FRP）。
替代……适用？感觉意思有点不太通

2018-11-16 07:25 UTC, li-bei commented on 2018-08-20-swift-property-observers.md
> +Swift 中有两种属性：*存储属性*，它们将状态和对象相关联；*计算属性*，则根据该状态执行计算。例如，
可以直接用 dfn tag

2018-11-16 08:12 UTC, kylinroc commented on 2018-08-20-swift-property-observers.md
> +需要注意的是当属性在初始化方法中进行赋值时，不会触发观察器的代码。从 Swift4.2 开始，你可以将赋值逻辑包装在 `defer` 代码块来解决这个问题，但这是[一个很快就会被修复的问题](https://twitter.com/jckarter/status/926459181661536256)，因此你不需要依赖于这种行为。
「不需要」感觉不太对，「不应该」要贴近原文一点

2018-11-16 08:14 UTC, wuqiuhao commented on 2018-08-20-swift-property-observers.md
> +需要注意的是当属性在初始化方法中进行赋值时，不会触发观察器的代码。从 Swift4.2 开始，你可以将赋值逻辑包装在 `defer` 代码块来解决这个问题，但这是[一个很快就会被修复的问题](https://twitter.com/jckarter/status/926459181661536256)，因此你不需要依赖于这种行为。
嗯 是的！

2018-11-16 08:17 UTC, kylinroc commented on 2018-08-20-swift-property-observers.md
> +- 新轨道对象的音频信息会被加载并播放
这里应该和原文一样用有序列表

2018-11-16 08:25 UTC, wuqiuhao commented on 2018-08-20-swift-property-observers.md
> +- 新轨道对象的音频信息会被加载并播放
好

2018-11-16 09:08 UTC, kylinroc commented
LGTM.

2019-01-27 05:43 UTC, croath commented on 2018-08-20-swift-property-observers.md
> +  现代软件开发已经被视为可能成为 Goldbergian 装置的典范。然而在进行一些远程操作时，它将显得更加清晰。
https://zh.wikipedia.org/wiki/魯布·戈德堡機械

2019-01-28 07:25 UTC, skyline75489 commented on 2018-08-20-swift-property-observers.md
> +编程过程中我们通常想要避免引入副作用，因为它会导致难以推断程序的行为。但很多 Objective-C 开发者已经依赖于这种特性，他们会根据需要在 getter 或 setter 中注入各种额外的行为。
“导致”后面缺少宾语，不太符合汉语的表达。可以考虑翻译成“它会导致程序的行为难以推断”。

2019-01-28 07:28 UTC, skyline75489 commented on 2018-08-20-swift-property-observers.md
> +你甚至可以像[*捕鼠记* 中描绘的场景](https://www.youtube.com/watch?v=TVAhhVrpkwM) 一样，将行为与多个观察属性级联起来
句尾缺一个句号

2019-01-28 07:29 UTC, skyline75489 commented on 2018-08-20-swift-property-observers.md
> +有时，你希望对类型确定的值增加额外的约束。
这里感觉有点不准确，我理解是类型“接受”的值。

2019-01-28 07:31 UTC, skyline75489 commented
总体质量还是可以的，Thanks!

2019-02-05 10:32 UTC, rickytan commented on 2018-08-20-swift-property-observers.md
> +正因为如此，我们才可以获取更一致的语义，并更好地保证键值观察（KVO）和健值编码（KVC）等属性交互机制。
键值，typo

2019-02-05 10:36 UTC, rickytan commented on 2018-08-20-swift-property-observers.md
> +很酷, 对吗?
下划线格式保留

2019-02-11 02:31 UTC, croath commented
看着挺好的，去掉英文原文吧

2019-02-11 02:54 UTC, croath requested changes

2019-02-11 02:54 UTC, croath commented on 2018-08-20-swift-property-observers.md
> +  Modern software development has become what might be seen as
这里？

2019-02-11 03:26 UTC, croath approved these changes

2019-02-11 03:26 UTC, merged

2019-02-11 03:26 UTC, croath commented
Cool, let's ship it for a try.

2019-02-11 03:35 UTC, wuqiuhao commented
部分段落的标题 原文忘记移除了 我又提了一个PR。