Translate CMMotion​Activity
NSHipster/articles-zh-Hans pull request #8
Opened 2018-09-17 16:37 UTC by kylinroc

2018-09-18 17:32 UTC, LiLejia commented
不需要保留英文吧。

2018-09-18 17:34 UTC, croath commented
review 的时候先留英文，方便对比，最后没问题一次性删除。

2018-09-18 17:55 UTC, LiLejia requested changes

2018-09-18 17:55 UTC, LiLejia commented on 2018-09-10-cmmotionactivity.md
> +经过几个版本的系统与硬件更新，苹果的设备变得擅长于区分运动的不同意义。在你跑去尝试自己实现前，停下来考虑一下使用这周文章中讨论的内置 API。
Means 是方式手段的意思。
Run off 的话，应该是类似于快速完成之类的意思。

2018-09-18 17:55 UTC, LiLejia commented on 2018-09-10-cmmotionactivity.md
> +经过几个版本的系统与硬件更新，苹果的设备变得擅长于区分运动的不同意义。在你跑去尝试自己实现前，停下来考虑一下使用这周文章中讨论的内置 API。
在你跑去�尝试自己实现前 多了个奇怪的字符。

2018-09-18 17:55 UTC, LiLejia commented on 2018-09-10-cmmotionactivity.md
> +在 iOS 和 watchOS 上，`CMMotionActivityManager` 处理设备中传感器的原始数据并告诉你（有多确定）用户是否正在移动，和用户是在行走、跑步、骑行或者开车。
(to what degree of certainty) 
确定的程度？

2018-09-18 17:55 UTC, LiLejia commented on 2018-09-10-cmmotionactivity.md
> +`CMMotionActivityManager` 由 Core Motion 框架提供。支持 Core Motion 的设备都装备了一个运动辅助处理器。通过使用专用硬件，系统可以将所有传感器处理工作从 CPU 上移除掉，并减少电量的使用。
`coprocessor`  官方译名是 `协处理器`。

2018-09-18 17:55 UTC, LiLejia commented on 2018-09-10-cmmotionactivity.md
> +`CMMotionActivityManager` 由 Core Motion 框架提供。支持 Core Motion 的设备都装备了一个运动辅助处理器。通过使用专用硬件，系统可以将所有传感器处理工作从 CPU 上移除掉，并减少电量的使用。
`Onload` = `加载`
`Offload` 是不是有别的翻译惯例？

2018-09-18 17:55 UTC, LiLejia commented on 2018-09-10-cmmotionactivity.md
> +`CMMotionActivity` 对每种运动类型都有一个布尔值属性，并且还有还有一个设备是否停滞的属性。这似乎违反直觉，逻辑上来说你在同一时间只能步行或者开车，但不能一起进行。
`stationary` -> 处于静止状态是不是更好些？

2018-09-18 17:55 UTC, LiLejia commented on 2018-09-10-cmmotionactivity.md
> +每个 `CMMotionActivity` 对象还包括了一个其值可能为 `.low`、`.medium` 或 `.high` 的 `confidence` 属性。不幸的是，文档没有提供多少关于这些值的有用信息，或者如何使用。对于这种情况，推荐使用一种经验性的方法：实际测试你的应用，观察不同情况下出现的 `confidence` 值，使用这些信息来修正应用的行为。
> about what any of these values mean, or how they should be used.

没有多少这些值究竟是什么意思，也没告诉我们该如何使用。
`or` 不是`或`，是 `neither...or` 里的 `既不是...也不是` 吧。

2018-09-18 17:55 UTC, LiLejia commented on 2018-09-10-cmmotionactivity.md
> +`CMMotionActivityManager` 是 Core Motion 里那些好用 API 的其中一个，你可以使用它来构造沉浸、反应灵敏的应用。
> immersive, responsive

沉浸般的、快速响应的？

2018-09-18 17:55 UTC, LiLejia commented on 2018-09-10-cmmotionactivity.md
> +如果你还没有考虑过将设备运动信息纳入应用的可能性（或者可能你很久没有关注过 Core Motion），你可能会被它能做到的事情惊讶到。
> the potential

潜力，不是可能性。

2018-09-19 13:14 UTC, kylinroc commented on 2018-09-10-cmmotionactivity.md
> +经过几个版本的系统与硬件更新，苹果的设备变得擅长于区分运动的不同意义。在你跑去尝试自己实现前，停下来考虑一下使用这周文章中讨论的内置 API。
run off 就是跑掉、离开这类意思吧，在这里我理解是，假如有人看到这就不看了，跑去自己实现。

2018-09-19 13:16 UTC, kylinroc commented on 2018-09-10-cmmotionactivity.md
> +在 iOS 和 watchOS 上，`CMMotionActivityManager` 处理设备中传感器的原始数据并告诉你（有多确定）用户是否正在移动，和用户是在行走、跑步、骑行或者开车。
感觉用「有多确定」比较像中文表述，而且可以和句子连在一起。🤔

2018-09-19 13:23 UTC, li-bei commented on 2018-09-10-cmmotionactivity.md
> +`CMMotionActivityManager` 由 Core Motion 框架提供。支持 Core Motion 的设备都装备了一个运动辅助处理器。通过使用专用硬件，系统可以将所有传感器处理工作从 CPU 上移除掉，并减少电量的使用。
卸载？

2018-09-19 13:25 UTC, li-bei commented on 2018-09-10-cmmotionactivity.md
> +`CMMotionActivity` 对每种运动类型都有一个布尔值属性，并且还有还有一个设备是否停滞的属性。这似乎违反直觉，逻辑上来说你在同一时间只能步行或者开车，但不能一起进行。
👌

2018-09-19 13:28 UTC, kylinroc commented on 2018-09-10-cmmotionactivity.md
> +每个 `CMMotionActivity` 对象还包括了一个其值可能为 `.low`、`.medium` 或 `.high` 的 `confidence` 属性。不幸的是，文档没有提供多少关于这些值的有用信息，或者如何使用。对于这种情况，推荐使用一种经验性的方法：实际测试你的应用，观察不同情况下出现的 `confidence` 值，使用这些信息来修正应用的行为。
👌

2018-09-19 13:31 UTC, kylinroc commented on 2018-09-10-cmmotionactivity.md
> +如果你还没有考虑过将设备运动信息纳入应用的可能性（或者可能你很久没有关注过 Core Motion），你可能会被它能做到的事情惊讶到。
👌

2018-09-19 16:22 UTC, LiLejia commented
LGTM 👍

2018-09-19 16:55 UTC, croath commented
LGTM.

质量上乘，文章本身也很有意思。请去掉英文原文吧。

2018-09-19 17:50 UTC, kylinroc commented
@croath Done.

2018-09-20 04:06 UTC, merged